### ISSUE TITLE
1) Función que muestre cartel de presentación.

### ISSUE THREAD

**Issue by franciscodevs** [ispc-programador2022/a7g2#2]
Crear la función ```bienvenida``` y guardarlo en un archivo llamado ```bienvenida.py``` en la carpeta ```funciones```

**Comment by vzta** [comment]
Se cierra, issue, aunque no se necesita usar print ya que usás la función return, otro dato a tener en cuenta es que la consigna dice "crear una función que admita dos enteros" por lo que no es necesario retornar esos valores.
